#!/bin/bash
# strip everything host-specific or regenerable
set -eu
apt-get clean
rm -rf /var/lib/apt/lists/* /var/cache/apt/*.bin
rm -f /etc/ssh/ssh_host_*            # regenerated by ssh-hostkeys-regen.service on first boot
: > /etc/machine-id; rm -f /var/lib/dbus/machine-id
rm -f /etc/resolv.conf; ln -s ../run/NetworkManager/resolv.conf /etc/resolv.conf 2>/dev/null || true
find /var/log -type f -delete
rm -f /root/.bash_history /home/*/.bash_history
test ! -e /var/lib/tailscale/tailscaled.state
